### PR TITLE
Redshift: Set Rendersettings actually apply `multilayer_exr` and `force_combine`

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Fix applying of **Force combine beauty and AOVs into a single file** and **Multipart EXR** in Redshift Rendersettings from settings defined in AYON settings.

## Additional info

The settings already existed but seemed to have been used nowhere - even back in OpenPype.

Note: There has been some discussion that Multilayer is not the same as Multipart so either the settings name and label is wrong, or we're setting the wrong attribute here? Any clue @m-u-r-p-h-y @antirotor ?

## Testing notes:

1. Change settings
```
ayon+settings://maya/render_settings/redshift_renderer/multilayer_exr
ayon+settings://maya/render_settings/redshift_renderer/force_combine
```
2. Launch Maya, set redshift as renderer.
3. Click "AYON > Set Render Settings" in menu in Maya
4. The Redshift render settings should now have been updated.

image

### CODE REVIEW

**Review by m-u-r-p-h-y — CHANGES_REQUESTED** [review]
it only works partially for me. The attributes from `Common` section of `Render Globals` are set correctly but other attributes are untouched

image

**Comment by m-u-r-p-h-y** [comment]
regarding the multilayer and multipart this is the way I understand the RS settings

image

Force combine beauty and AOVs into single file = multilayer
Multipart EXR = multipart

**Comment by BigRoy** [comment]
> it only works partially for me. The attributes from `Common` section of `Render Globals` are set correctly but other attributes are untouched
> 
> image

Should be fixed - it seems updated in recent Redshift versions, so I've justed matched it. Tested with Maya 2024.2 and Redshift 3.6.03.

**Comment by BigRoy** [comment]
@m-u-r-p-h-y you'd need to build and redeploy the addon for updated settings, yes.

**Comment by m-u-r-p-h-y** [comment]
> @m-u-r-p-h-y you'd need to build and redeploy the addon for updated settings, yes.
will do

> If still not working - what Maya version and Redshift version are you using?

M2025.1
RS3.6.04

**Comment by BigRoy** [comment]
> M2025.1
> RS3.6.04

Just to be sure - you did try with a re-uploaded addon package @m-u-r-p-h-y ?

**Review by m-u-r-p-h-y — APPROVED** [review]
recreated and reuploaded the addon.

all options are propagated correctly. (even the custom attributes) 
image
image

**Pull request merged**
