### PR TITLE
Enable/disable frame range attribute definitions based on "Export Animation Data" toggle

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Enable/disable frame range attribute definitions based on "Export Animation Data" toggle

## Additional info

Requires PR https://github.com/ynput/ayon-core/pull/935

## Testing notes:

1. Publisher UI instance attributes should toggle "frame range" attributes based on the "Export Animation Data" toggle set on the instance.

image
image

### CODE REVIEW

**Review by LiborBatek — APPROVED** [review]
LGTM

Once disabled the ```Export anim data``` , options for frame range etc got greyed out and disabled too...

Screenshot 2024-10-07 141902

**Review by moonyuet — APPROVED** [review]

**Comment by BigRoy** [comment]
Adding `bump minor` label. Right @iLLiCiTiT ?

**Comment by BigRoy** [comment]
@iLLiCiTiT the required PR is now merged into `ayon-core` with 1.0.3 being the current last release with out. The next release would then be `>1.0.3`. Should I now mark the compatibility requirement to `>1.0.3` or should I wait for the `ayon-core` release itself to have occurred?

**Comment by iLLiCiTiT** [comment]
You can use `>1.0.3`. But I would wait with merge for ayon-core release.

**Comment by BigRoy** [comment]
Should be ready now 🚀

**Review by LiborBatek — COMMENTED** [review]
Even tho I have used latest ```ayon-core``` develop branch as this [PR](https://github.com/ynput/ayon-core/pull/935) been merged already...

I cant locate the toggle for ```Export Animation``` within the publisher UI!

image

Any idea whats wrong??

**Comment by BigRoy** [comment]
It's on the `Maya USD Export` only @LiborBatek

**Review by LiborBatek — APPROVED** [review]
@BigRoy haha, sry my bad! thx

Works well...

image

**Comment by BigRoy** [comment]
@iLLiCiTiT feel free to merge - maybe you want a last look?

**Pull request merged**
