### PR TITLE
Load to Maya USD Proxy Shape using AYON Entity URI for AYON USD Resolver

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Load to Maya USD Proxy Shape using AYON Entity URI for AYON USD Resolver

## Additional info

Matches this AYON Houdini PR: https://github.com/ynput/ayon-houdini/pull/26 and hence also highlights what we may want to de-duplicate and re-use code for.

image

image

### TODO

 - [x] Allow to toggle in settings whether path should be AYON Entity URI or regular resolved path

## Testing notes:

1. Upload new addon
2. Enable `ayon+settings://maya/load/MayaUsdLoader/use_ayon_entity_uri`
3. Load USD to Maya USD Proxy

image

4. It should use the AYON Entity URI as filepath.
5. It should work with the AYON USD resolver.

### CODE REVIEW

**Comment by Lypsolon** [comment]
Hello @BigRoy i see that this maya addon needs a core version of 0.4.1+ and im not sure what branch i should use for to build the right core addon for that ?

**Comment by BigRoy** [comment]
> i see that this maya addon needs a core version of 0.4.1+ and im not sure what branch i should use for to build the right core addon for that ?

This should work fine with any recent version of `ayon-core`. So `develop` branch should be fine, or even the `0.4.4` release if you'd like.

**Review by Lypsolon — COMMENTED** [review]
My Domain Knowledge of Maya is 0. 
but i see the expected Object in Maya loaded with a usd. 

i have no idea if its using the uri or not tho. 
i believe its an normal path tho. 
image


[Edit] i activated the settings for entity uri. 
image

**Comment by BigRoy** [comment]
> * Upload new addon
> 
> * Enable `ayon+settings://maya/load/MayaUsdLoader/use_ayon_entity_uri`
> 
> * Load USD to Maya USD Proxy
> 
> * It should use the AYON Entity URI as filepath.
> 
> * It should work with the AYON USD resolver.

1. @Lypsolon did you have the setting enabled?
2. I have a feeling you're using "Reference USD" or whatever (which is a maya reference, which I'm not sure would even support the resolver - I'd need to try that! still) but this is about the **"Load USD to Maya Proxy"** loader.

**Review by Lypsolon — APPROVED** [review]
Tested on almalinux 9 Maya20205 

it was possible to load an asset build by using the contribution workflow via Houdini. 

materials where assigned correctly, asset loaded, uri was with the correct version and not with latest.

**Pull request merged**
