### PR TITLE
Implement Maya USD Export Chaser to Filter Properties

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Implement Maya USD Export Chaser to Filter Properties using a SideFX Houdini style pattern matching for all prim properties

## Additional review information

For explanation on how the pattern works, see [SideFX Houdini Pattern Matching in Parameters](https://www.sidefx.com/docs/houdini/network/patterns.html) which it is loosely based on.

image

Results in:

image

```usda
#usda 1.0
(
    defaultPrim = "char_hero"
    metersPerUnit = 0.01
    upAxis = "Y"
)

def Xform "char_hero" (
    kind = "component"
)
{
    double3 xformOp:translate = (-0.4334395286605499, 0.8835878002001145, -0.6190157988997917)
    uniform token[] xformOpOrder = ["xformOp:translate"]

    def Mesh "pCube1"
    {
    }
}
```

Note how the mesh contains no properties at all - they are completely stripped from the written USD file.

### TODO

- [x] Improve attribute definition tooltip to describe the available pattern and maybe some examples.
- [x] Add to settings to enable/disable the plug-in and potentially set up a default value.

Added `ayon+settings://maya/publish/CollectMayaUsdFilterProperties`

image

## Testing notes:

1. A new attribute "USD Filter Properties" should appear on Maya USD instances
2. When any pattern is entered, then only those properties would be exported into the output file. For example:

- Only include xforms: `xformOp*`
- Everything but xforms: `* ^xformOp*`
- Everything but mesh point data: `* ^extent ^points ^faceVertexCounts ^faceVertexIndices ^primvars*`

### CODE REVIEW

**Comment by BigRoy** [comment]
This PR may also solve https://github.com/ynput/ayon-maya/issues/82 but only partially.
This PR does not:
- Strip prim definitions that are empty without properties
- Turn anything into `over` instead of `def`

**Comment by LiborBatek** [comment]
yeah, its def very techy thing :) ...from artist pov at least (e.g. me :) 

I would like to recommend if that Ayon setting disabled (USD export chaser) then no new UI items shown in the publisher UI...if possible

and yes, disabled as defaults sounds right too!

**Comment by moonyuet** [comment]
Checked in the published usd file: The xform data is there.
image
When the usd is imported back to Houdini, it appeared not to load anything(which is expected). When checking the geometry speadsheet, all xform attributes are loaded
image

**Comment by moonyuet** [comment]
Tested with second scanerio where the xform is not included: (It shows all the vertex data of the meshes)
image
As the xform data is not exported, which means all the transforms of the meshes become zero when importing back to houdini
image
All the geometries would be at zero transform
image

This is how the usd export without the filter looks like, which means the filtering function works as expected.
image

**Review by moonyuet — APPROVED** [review]
See comments above

**Comment by BigRoy** [comment]
> I would like to recommend if that Ayon setting disabled (USD export chaser) then no new UI items shown in the publisher UI...if possible
> 
> and yes, disabled as defaults sounds right too!

Correct - that should be the behavior now.

**Pull request merged**
