### PR TITLE
Maya: Fix update reference without reference node showing wrong error message

### LINKED ISSUE #9: Maya: ReferenceLoader update failure due to no reference node reports wrong message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Whenever you have a Maya scene that has loaded containers of `ReferenceLoader` using maya references, but for whatever reason the Maya Reference node does not exist anymore yet the container is still lingering around. When trying to update this error occurs:
```python
// Warning: SceneInventory : Update failed
// Traceback (most recent call last):
//   File "E:\dev\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
//     update_container(item, item_version)
//   File "E:\dev\ayon-core\client\ayon_core\pipeline\load\utils.py", line 532, in update_container
//     return Loader().update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_reference.py", line 266, in update
//     super(ReferenceLoader, self).update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 890, in update
//     reference_node = lib.get_reference_node(members, self.log)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 4288, in get_reference_node
//     assert references, "No reference node found in container"
// AssertionError: No reference node found in container
```

However, this dialog shows to the user:
image

The message is incorrect since the version being updated to exists just fine.

### Expected Behavior:

The displayed message to the artist should be correct.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load a Maya reference
2. In outliner enable > Display > Ignore "Hidden in outliner"
3. In `AVALON_CONTAINERS` add an object into the reference container (just so that maya does not auto-delete it in next step)
4. On the loaded maya reference remove the reference (via Maya itself, not via AYON tools)
5. Container object set should still exist, but no reference node
6. Via Ayon > Manage.. try to set the version of the container - it will fail.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
// Warning: SceneInventory : Update failed
// Traceback (most recent call last):
//   File "E:\dev\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
//     update_container(item, item_version)
//   File "E:\dev\ayon-core\client\ayon_core\pipeline\load\utils.py", line 532, in update_container
//     return Loader().update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_reference.py", line 266, in update
//     super(ReferenceLoader, self).update(container, context)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 890, in update
//     reference_node = lib.get_reference_node(members, self.log)
//   File "E:\dev\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 4288, in get_reference_node
//     assert references, "No reference node found in container"
// AssertionError: No reference node found in container
```

### Additional context:

_No response_

### PR DESCRIPTION
**Pull request by BigRoy**
> [!NOTE] 
> PR moved from https://github.com/ynput/ayon-core/pull/465

## Changelog Description

Raise `LoadError` instead of `assert` on no reference node found on Maya reference update

## Additional info

Fixes #9 

Note: This now currently shows no dialog.

## Testing notes:

Easiest way to get into a 'broken' state for the ReferenceLoader:

1. Load a Maya reference
2. In outliner enable > Display > Ignore "Hidden in outliner"
3. In `AVALON_CONTAINERS` add an object into the reference container (just so that maya does not auto-delete it in next step)
4. On the loaded maya reference remove the reference (via Maya itself, not via AYON tools)
5. Container object set should still exist, but no reference node
6. Via Ayon > Manage.. try to set the version of the container - it will fail.

### CODE REVIEW

**Review by LiborBatek — COMMENTED** [review]
I have followed the steps....as said, no any error raised via UI just the following log in the script editor:

```
# Traceback (most recent call last):
#   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 366, in <lambda>
#     lambda: self._show_version_dialog(item_ids, active_repre_id)
#   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 843, in _show_version_dialog
#     self._update_containers_to_version(
#   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1032, in _update_containers_to_version
#     self._update_containers(item_ids, versions)
#   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 1007, in _update_containers
#     update_container(container, item_version)
#   File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\load\utils.py", line 539, in update_container
#     return Loader().update(container, context)
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\plugins\load\load_reference.py", line 256, in update
#     super(ReferenceLoader, self).update(container, context)
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\plugin.py", line 808, in update
#     raise LoadError("No reference node found in container")
# ayon_core.pipeline.load.utils.LoadError: No reference node found in container
```
image

**Comment by BigRoy** [comment]
Thanks @LiborBatek - the lack of UI dialog on the error is indeed an issue, but a separate one from reporting the correct error starting here. The UI issue would need changes in `ayon-core`. After this will be merged I can make a follow-up issue on Ayon core.

**Comment by iLLiCiTiT** [comment]
Handling of errors in scene inventory is a different beast.

**Comment by LiborBatek** [comment]
@BigRoy thx for clarification, as I wasnt sure if thats all needed for Approval review, call it my lack of knowledge :)

**Review by LiborBatek — APPROVED** [review]
Works ok.

**Pull request merged**
