### PR TITLE
Fix publishing USD from maya with asset/shot contributions enabled

### PR DESCRIPTION
**Pull request by BigRoy**
Fix a bug where USD `usdAsset` (asset and shot) contributions fail to publish.

### Additional Info

Clickup AY-6115

### Testing notes

1. Publish a USD file from Maya should not raise any errors WITH USD Contribution checkbox enabled
2. Publish a USD file from Maya should not raise any errors WITH USD Contribution checkbox disabled

The USD contribution checkbox:
> Thanks - on a USD instance there should be a setting on the instance under a section **USD Contribution** which has **Enable** checkbox.
> 
> See also screenshots [here](https://community.ynput.io/t/ayon-usd-workflow-guide/1545/2?u=bigroy).

### CODE REVIEW

**Comment by BigRoy** [comment]
Seems another fix was missing - copied that over now as well.
It should work now:

image

**Comment by BigRoy** [comment]
This PR will need to be merged to fix the USD integration after the ayon-maya separation. Anyone can review this @antirotor and merged so we don't leave maya in the broken state?

@moonyuet are you able to test-run this?

Client also reported this issue.

**Review by moonyuet — APPROVED** [review]
Tested successfully in Maya 2025 with or without `Include User Defined Attributes`

**Comment by BigRoy** [comment]
> Tested successfully in Maya 2025 with or without `Include User Defined Attributes`

Thanks - on a USD instance there should be a setting on the instance under a section **USD Contribution** which has **Enable** checkbox.

See also screenshots [here](https://community.ynput.io/t/ayon-usd-workflow-guide/1545/2?u=bigroy).

**Comment by moonyuet** [comment]
> > Tested successfully in Maya 2025 with or without `Include User Defined Attributes`
> 
> Thanks - on a USD instance there should be a setting on the instance under a section **USD Contribution** which has **Enable** checkbox.
> 
> See also screenshots [here](https://community.ynput.io/t/ayon-usd-workflow-guide/1545/2?u=bigroy).
> 
> 545ce035e34eceab2a39337c587ceeb78a9162a8


image
image

**Pull request merged**
