### PR TITLE
Support underscore delimiter for yeti UDIM textures

### LINKED ISSUE #117: AY-6769_Yeti UDIM underscore delimiter
### Please describe the enhancement you have in mind and explain what the current shortcomings are?

expecting the UDIM to be prefixed with . instead of _ 
So .1001.png instead of _1001.png

### How would you imagine the implementation of the enhancemenent?
_No response_

### Describe alternatives you've considered:
_No response_

### Additional context:
()
_(might be a private channel)_

_This issue was automatically created from Clickup ticket [AY-6769](https://app.clickup.com/t/86c0cr6y1)_

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Correctly collect sequences with `_1001.exr` instead of only delimited by `.` like `.1001.exr`. 

## Additional info

Fixes #117

This same function is also used for collecting Ornatrix textures - so it may be worth running a check of publishing ornatrix textures along as well.

## Testing notes:

1. Load a texture file in Yeti with `_` delimiter, like: `C:/projects/ayontest/asset/char_hero/publish/image/textureMain.Diffuse/v002/ynts_char_hero_textureMain.Diffuse_v002_<UDIM>.png`

image
image

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
The code looks good to me.
Tested with ornatrix rig. The changes does not affect the publish.
image

@LiborBatek can you do the test on Yeti?

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Does not work for me (did try 2 times and also built the ayon-maya addon for the second try) gives validation errors (enclosing the JSON file too)

Screenshot 2024-10-02 111039


Screenshot 2024-10-02 112603

And the full JSON log:

[publish-report-241002-11-25.json.txt](https://github.com/user-attachments/files/17227321/publish-report-241002-11-25.json.txt)

**Comment by BigRoy** [comment]
Thanks @LiborBatek can you show me the udim files on disk?

**Comment by BigRoy** [comment]
Actually - I think I've found it. For whatever reason my filename tested did have more than one dot in the filename so it passed another check. I think I may have fixed your case with https://github.com/ynput/ayon-maya/pull/129/commits/b882f60b5fadb9514817b195529f00a7cb5f8d35

Any chance it's easy for you to try again?

**Review by LiborBatek — APPROVED** [review]
Works fine now!

I have also checked the published ```yetiRig``` via loading it and inspect the asset,

All good!

image

**Pull request merged**
