### PR TITLE
AY-6654 Look: Fix None values in collecting and applying attributes

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

This fixes a case where looks failed to apply due to `None` values being present in the collected attributes.
These will now be ignored in collected. There's an edge case where Maya returns `None` for string attributes that have no values set - those are captured now explicitly to just `""` to still collect and apply them later.

Existing looks will now also apply correctly with `None` value in their look attributes, but the attributes with `None` values will be ignored with a warning.

## Testing notes:

1. Load a model reference
2. Create a string attribute, e.g. `test`
3. Do not set any value for it.
    - Maya will return None for this attribute, e.g. select the object and run:
```python
from maya import cmds
print(cmds.getAttr(".test"))
```
It will print `None`.
4. Publish the look for this mesh
5. The published `.json` file should have attribute value for `test` set to `""`

To test the 'backwards compatible fix':
- Publish the same look with `develop` branch. The value will be `null` in the `.json` file.`
- OR, just open the last published `.json` file, and edit the `""` value to `null`

Then, confirm that applying the look succeeds without errors but with a warning regarding the `None` value when applying with this PR. For example in my test run it logged:

```
// Warning: ayon_maya.api.lib : Skipping setting |_GRP|cube_GEO.test with value 'None'
```

### CODE REVIEW

**Review by LiborBatek — COMMENTED** [review]
It all works speaking of the new way of treating the occasion when no any entry in the custom attribute present...so all good on this front!

I have issue when trying the "backward compatible" steps as it throws an error when ```None``` value present in the ```JSON``` so I dont get any warning only instead.

```
// Warning: ayon_maya.api.lib : Skipping setting |screwD_modelMain_01_:_GRP|screwD_modelMain_01_:model_GRP|screwD_modelMain_01_:Body_GEO.custom with value 'None'
# Traceback (most recent call last):
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\tools\mayalookassigner\app.py", line 286, in on_process_selected
#     assign_look_by_version(
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1889, in assign_look_by_version
#     apply_shaders(relationships, shader_nodes, nodes)
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 2027, in apply_shaders
#     apply_attributes(attributes, nodes_by_id)
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1738, in apply_attributes
#     set_attribute(attr, value, node)
#   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1694, in set_attribute
#     kwargs = ATTRIBUTE_DICT[value_type]
# KeyError: 'NoneType'
```

**Comment by BigRoy** [comment]
> It all works speaking of the new way of treating the occasion when no any entry in the custom attribute present...so all good on this front!
> 
> I have issue when trying the "backward compatible" steps as it throws an error when `None` value present in the `JSON` so I dont get any warning only instead.
> 
> aka it seems that it still fails... (even tho my asset got the look assigned anyway)
> 
> ```
> // Warning: ayon_maya.api.lib : Skipping setting |screwD_modelMain_01_:_GRP|screwD_modelMain_01_:model_GRP|screwD_modelMain_01_:Body_GEO.custom with value 'None'
> # Traceback (most recent call last):
> #   File "c:\Work\REPO\ayon-maya\client\ayon_maya\tools\mayalookassigner\app.py", line 286, in on_process_selected
> #     assign_look_by_version(
> #   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1889, in assign_look_by_version
> #     apply_shaders(relationships, shader_nodes, nodes)
> #   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 2027, in apply_shaders
> #     apply_attributes(attributes, nodes_by_id)
> #   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1738, in apply_attributes
> #     set_attribute(attr, value, node)
> #   File "c:\Work\REPO\ayon-maya\client\ayon_maya\api\lib.py", line 1694, in set_attribute
> #     kwargs = ATTRIBUTE_DICT[value_type]
> # KeyError: 'NoneType'
> ```

That's exactly the error this PR should solve. It applies the shaders yes, but fails to apply all attributes.
Did you test that "applying" with the `null` in the JSON file with this PR enabled?
(You will need to launch Maya while in this branch! So restart if you hadn't)

**Comment by BigRoy** [comment]
Sorry, somehow my previous push of the commit failed. It was missing this: https://github.com/ynput/ayon-maya/pull/89/commits/fc52bb1eb3c1d5c5e581f781e76a2aa5871d8634

**Review by LiborBatek — APPROVED** [review]
Now all good and no errors thrown...

Just that Warning message as mentioned in testing steps.

Good to go!

**Pull request merged**
